const { EmbedBuilder } = require('discord.js');
const config = require("../config.js");
const { description } = require('./ping.js');


module.exports = {
    name: "joke",
    description: "tells a joke",
    permissions: "0x0000000000000800",

    run: async (client, interaction, lang) => {
        try {
            let majak = getRandomNumber4();
            const embed_joke = new EmbedBuilder()
                .setColor("Random")
                .setTitle(`${jokes[majak]}`)

            interaction.reply({ embeds: [embed_joke] })

        } catch (error) {
            console.log(error);


        }
    }
}

const jokes = [
    "I like my coffee like I like my women—hot, strong, and all over my lap.",
    "Sex is like air; it’s not a big deal unless you’re not getting any.",
    "Condoms are like Cinderella’s shoes—if it doesn’t fit, it’s probably not yours.",
    "My girlfriend told me to go deeper… so I took up philosophy.",
    "What’s the difference between your job and your wife? After five years, your job will still suck.",
    "I asked my wife what she wanted for Valentine’s—she said, 'something with diamonds,' so I got her a deck of cards.",
    "I have the body of a porn star… unfortunately, it’s Ron Jeremy.",
    "Life is like a penis—simple, relaxed, and free… until a woman makes it hard.",
    "Why did the sperm cross the road? Because I wore the wrong socks.",
    "Women fake orgasms, but men fake entire relationships.",
    "My girlfriend told me to whisper dirty things in her ear… so I said, 'The kitchen.'",
    "What’s the difference between a joke and two d*cks? You can’t take a joke.",
    "I like my women like I like my bacon—hot, greasy, and ready in five minutes.",
    "They say love is in the air… maybe that’s why I’m suffocating.",
    "If sex is a pain in the ass, you’re doing it wrong.",
    "I bought my girlfriend a vibrator—now she texts me less.",
    "I tried phone sex once, but the hole in my phone was too small.",
    "She said size doesn’t matter… but she’s still buying a bigger TV.",
    "I told my wife she should embrace her mistakes—so she hugged me.",
    "If a man says he’ll fix something, he will—no need to remind him every six months.",
    "Condoms are like Cinderella’s shoes—if it doesn’t fit, it’s probably not yours.",
    "Sex is like air; it’s not a big deal unless you’re not getting any.",
    "What’s 6 inches long, has a head, and drives women crazy?A $100 bill.",
    "Love is like a fart… if you have to force it, it's probably crap.",
    "My girlfriend told me to be more in touch with my feminine side, so I crashed the car.",
    "My wife said I never listen to her… at least I think that's what she said.",
    "Relationships are like algebra. Have you ever looked at your X and wondered Y?",
    "My girlfriend said I'm terrible at directions, so I packed my bags and right.",
    "Love is sharing your popcorn. Marriage is when they take it and leave you with the crumbs.",
    "Dating is like a walk in the park… Jurassic Park.",
    "My girlfriend told me I should do lunges to stay in shape. That would be a big step forward.",
    "The key to a successful relationship is honesty. So, I told my girlfriend I have a second one.",
    "A good relationship is like a casserole—only those who make it know what goes in.",
    "Marriage is like a deck of cards. In the beginning, all you need is two hearts and a diamond. By the end, you're looking for a club and a spade.",
    "My wife asked me what's on TV… dust, I said.",
    "I asked my wife where she wanted to go for our anniversary. She said, \"Somewhere I've never been.\" I said, \"Try the kitchen.\"",
    "Marriage is just texting each other, \"Do we need anything from the store?\" until one of you dies.",
    "My wife said she wanted space. I locked her outside.",
    "I married my wife for her looks, but not the ones she's giving me now.",
    "The secret to a happy marriage? A husband who is deaf and a wife who is blind.",
    "My wife and I always hold hands. If I let go, she starts shopping.",
    "Why do married men die before their wives? Because they want to.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "My ex left me because of my obsession with pasta. I'm feeling cannelloni right now.",
    "My girlfriend broke up with me because I quote Linkin Park too much. But in the end, it doesn't even matter.",
    "My ex and I had a lot of communication issues… I'd text, she'd ignore.",
    "My ex said I never listen. Or something like that.",
    "I ran into my ex today… then I put it in reverse and ran over her again.",
    "My ex-girlfriend said she was missing me. I told her to check under the bed.",
    "Breakups are like a mirror. It's better to leave them broken than hurt yourself trying to fix it.",
    "My ex asked me to get back together. I told her I don't date fossils.",
    "My ex upgraded to a new man. Too bad she's still running the same old drama.",
    "My ex told me I was childish. I told her to get out of my pillow fort.",
    "My girlfriend told me to take out the trash… I packed my bags.",
    "I asked my wife what she wanted for her birthday. She said, \"Nothing would make me happier than a diamond ring.\" So I got her nothing.",
    "A relationship is like Wi-Fi—when the connection is strong, it's great, but when it's weak, you start searching for better options.",
    "My wife says I have two faults: I don't listen, and… some other stuff.",
    "If a man says he'll fix something, he will. There's no need to remind him every six months.",
    "Arguing with a woman is like reading the software agreement. In the end, you just agree to everything.",
    "My wife told me to put the toilet seat down. I told her to put the lid up. We're now both dehydrated.",
    "Relationships are just two people constantly asking each other what they want to eat until they die.",
    "I told my girlfriend she drew her eyebrows too high. She looked surprised.",
    "I thought my wife was kidding when she said she wanted to go on a diet. It was the most fattening joke I ever made.",
    "My girlfriend said I never make her feel special… so I stopped talking to other girls.",
    "If a woman says, \"Do what you want,\" don't. It's a trap.",
    "My wife wanted me to take her somewhere expensive… so I took her to the gas station.",
    "If love is blind, why is lingerie so popular?",
    "I love my girlfriend, but sometimes she makes me feel like Google… she asks me everything but never listens to the answer.",
    "My wife said I should treat her like a queen… so I beheaded her.",
    "A husband is someone who, after taking out the trash, gives himself a trophy for \"helping around the house.\"",
    "My girlfriend said she needs more space. I sent her a map of the solar system.",
    "My girlfriend asked me if I believe in ghosts. I said no. Then she asked, \"So why are you ignoring me?\"",
    "I told my girlfriend I loved her, and she said, \"Thanks.\" I guess we're playing emotional poker now.",
    "Why did the banana go to the party? Because it was peeling kinky.",
    "What's the difference between your wife and your job? After five years, your job will still suck.",
    "My girlfriend told me to tie her up and do whatever I want… so I played Xbox.",
    "Why do girls love musicians? Because they know how to work their fingers.",
    "What's the difference between a lightbulb and a pregnant woman? You can unscrew a lightbulb.",
    "Why don't women trust men in bed? Because 90% of them are finishers, not starters.",
    "Why did the blonde bring a ladder to the bar? She heard the drinks were on the house.",
    "What do you call a woman who's really good at sex? A rare breed.",
    "What's the difference between a microwave and a woman? A microwave won't yell at you for pushing its buttons.",
    "What's the first thing a girl does when she wakes up? Puts on her clothes and goes home.",
    "What's long and hard and full of semen? A submarine.",
    "Why did the couple break up at the nudist beach? Because he couldn't keep it up.",
    "Why do lesbians make bad chess players? Because they always avoid the king.",
    "Why don't blind people skydive? It scares the hell out of the dog.",
    "Why do cannibals avoid clowns? Because they taste funny.",
    "What's the difference between sex and a Ferrari? I've actually had sex.",
    "Why do women love rich men? Because their wallets stay hard longer.",
    "What's the difference between a boyfriend and a sock? A sock doesn't cry when you stuff it in a drawer.",
    "What's the worst thing about dating a gymnast? You never know if she's cheating or just stretching.",
    "Why do men love women in yoga pants? Easy access to downward dog.",
    "What's the difference between sex and fishing? When you lie about fishing, people still respect you.",
    "What's the difference between an iPhone and your girlfriend? Your iPhone won't leave you for an Android user.",
    "Why do they call it a \"blowjob\"? Because \"job\" implies there's effort involved.",
    "Why don't women trust men? Because they pull out at the worst times—both in bed and in life.",
    "Why did the vibrator break up with the girl? It was tired of being the rebound.",
    "What's the most awkward moment during sex? When she says, \"That's it?\"",
    "My wife told me she'd do anything to make me happy… I told her to bring her best friend over.",
    "Why do women fake orgasms? Because they think we care.",
    "What's the difference between a G-spot and a golf ball? A guy will actually look for a golf ball.",
    "What do you call a guy with a small package? A minimalist.",
    "Why is a man's zipper called a fly? Because it's the only thing that moves that fast.",
    "Why did the banana break up with the vibrator? Because it found out it was being used for pleasure, not nutrition.",
    "What's the best thing about dating a homeless woman? You can drop her off anywhere.",
    "Why did the baker get arrested? He was caught pinching the buns.",
    "Why do they say love is blind? Because nobody would get laid if they could see each other sober.",
    "What do you call an IT guy who's bad in bed? A software engineer.",
    "Why don't lesbians get fat? Because they eat out all the time.",
    "I told my girlfriend she drew her eyebrows too high. She looked surprised.",
    "Why do men love curves? Because without them, they'd be lost.",
    "What do you call a guy who cries after sex? Uber.",
    "Why don't women trust men? Because the last time they did, they ended up with Eve and an apple.",
    "What's the difference between a pickpocket and a peeping Tom? One snatches watches, the other watches snatches.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a woman who knows where her husband is at all times? A widow.",
    "Why don't chickens tell dirty jokes? Because they might crack up.",
    "Why is Santa always so jolly? Because he knows where all the naughty girls live.",
    "What's long, hard, and full of seamen? A submarine.",
    "What do you call a nun in a wheelchair? Virgin Mobile.",
    "Why did the couple break up at the gym? Because the relationship wasn't working out.",
    "I walked in on my parents having sex. Worst 30 minutes of my life.",
    "What do you call a cheap circumcision? A rip-off.",
    "Why do guys like cars with big mufflers? Because they like their girls the same way—loud and full of hot air.",
    "What's the hardest part about dating a blind girl? You have to keep describing your size.",
    "Why did the condom fly across the room? It was pissed off.",
    "Why are boobs like a train set? They're meant for kids, but grown men can't stop playing with them.",
    "What's the worst thing about having a threesome? Sleeping in the wet spot.",
    "Why don't women trust men in bed? Because they keep pulling out at the last second.",
    "What's the difference between your wife and a mosquito? Mosquitoes stop sucking after you slap them.",
    "Why don't people do stand-up comedy naked? Because the mic isn't the only thing that shrinks under pressure.",
    "Why did the man refuse to have a threesome with twins? He said he didn't want to work double shifts.",
    "Why don't priests play hide and seek? Because good luck hiding when Father finds you.",
    "Why do girls love bad boys? Because they know they'll get punished.",
    "What's better than roses on your piano? Tulips on your organ.",
    "What's the difference between a drug dealer and a prostitute? A prostitute can wash her crack and sell it again.",
    "What's the hardest part about eating vegetables? The wheelchair.",
    "What do you call an adult film about depression? Inside Out.",
    "What's the difference between my ex and a refrigerator? The fridge doesn't fart when you pull your meat out.",
    "Why did the priest get kicked out of the church? Because he kept trying to turn wine into minors.",
    "What's a 6.9? A great time ruined by a period.",
    "What do tofu and a dildo have in common? They're both meat substitutes."
];

function getRandomNumber4() {
    return Math.floor(Math.random() * jokes.length)
}