const { EmbedBuilder } = require('discord.js');
const config = require("../config.js");
const { description } = require('./ping.js');


module.exports = {
    name: "wouldyourather",
    description: "tells a wouldyourather",
    permissions: "0x0000000000000800",
    run: async (client, interaction, lang) => {
        try {
            let random3 = getRandomNumber3();
        let user = interaction.options.getUser('mention') || interaction.user;

       
        interaction.reply(`**<@${user.id}>  ${wouldYouRatherQuestions[random3]}**`);
        } catch (error) {
            console.log(error);
            
            
        }
    }
}

const wouldYouRatherQuestions = [
    "Would you rather marry someone who loves you deeply but you feel nothing for or someone you love deeply but they feel nothing for you?",
    "Would you rather stay in a toxic relationship forever or be single and lonely forever?",
    "Would you rather know your partner's every past romantic/sexual detail or never know anything about their past?",
    "Would you rather catch your partner cheating on you once but never again or never know but they cheat occasionally?",
    "Would you rather be madly in love but poor or rich but in a passionless marriage?",
    "Would you rather have a partner who never compliments you but is loyal or constantly compliments you but is a flirt?",
    "Would you rather have a partner who is overly clingy or emotionally distant?",
    "Would you rather find out your partner was in love with their ex the whole time or secretly had a huge crush on your best friend?",
    "Would you rather be in a long-distance relationship forever or live together but never feel emotionally connected?",
    "Would you rather be with someone who is great in bed but terrible at communication or emotionally perfect but zero physical chemistry?",
    "Would you rather break someone's heart badly or have your heart completely shattered?",
    "Would you rather be dumped in public or ghosted without explanation?",
    "Would you rather be with a partner who's never over their ex or one who cheats but still claims to love you?",
    "Would you rather know your relationship has an expiration date or be blindsided by a breakup?",
    "Would you rather be cheated on by your soulmate or never find real love?",
    "Would you rather date someone who constantly brings up their ex or someone who never opens up about their past at all?",
    "Would you rather stay friends with an ex who broke your heart or completely erase them from your memory?",
    "Would you rather get back with an ex who hurt you deeply or never be in love again?",
    "Would you rather forgive a cheater and try to rebuild trust or never be able to trust anyone again?",
    "Would you rather date someone who's always honest but brutal or someone who tells white lies to protect your feelings?",
    "Would you rather have your parents choose your spouse or never be allowed to marry at all?",
    "Would you rather have in-laws who completely control your marriage or a partner who never stands up for you?",
    "Would you rather marry someone your family hates but you love or someone your family loves but you feel nothing for?",
    "Would you rather have a perfect spouse but horrible in-laws or a difficult spouse but amazing in-laws?",
    "Would you rather have a partner who's obsessed with their family or one who completely ignores them?",
    "Would you rather never have kids but be with your true love or have kids but in an unhappy marriage?",
    "Would you rather adopt a child and raise them alone or stay childless in a relationship?",
    "Would you rather have a spouse who works all the time but provides well or one who's always around but financially struggling?",
    "Would you rather never argue in a relationship but have no deep connection or fight often but be madly in love?",
    "Would you rather be stuck in a loveless marriage for life or never be able to marry at all?",
    "Would you rather have a partner who never cheats but is constantly broke or one who provides everything but has cheated once?",
    "Would you rather be with someone who makes millions but never has time for you or someone who earns little but gives you all their time?",
    "Would you rather win the lottery but your partner leaves you or stay poor but happily in love?",
    "Would you rather work a miserable job for wealth and comfort or struggle financially while chasing your passion?",
    "Would you rather find out your partner is only with you for your money or is deeply in love but terrible at managing money?",
    "Would you rather share every cent with your partner or never be allowed to talk about money in your relationship?",
    "Would you rather marry for financial security or for love knowing you'll struggle financially forever?",
    "Would you rather pay off all your partner's debts or let them struggle but keep your own money safe?",
    "Would you rather have a partner who spends recklessly or one who controls every cent of your finances?",
    "Would you rather live in luxury but never be in love or live paycheck to paycheck but in the happiest relationship?",
    "Would you rather have a partner who keeps small secrets or one who overshares everything?",
    "Would you rather find out your partner lied about their entire past or that they lied about their feelings for you?",
    "Would you rather be with someone who loves you but is a compulsive liar or someone who is brutally honest but emotionally cold?",
    "Would you rather find out your partner is in love with someone else but stays with you or that they secretly have another family?",
    "Would you rather accidentally reveal your partner's deepest secret or have them reveal yours to the world?",
    "Would you rather be with a partner who flirts with everyone but never cheats or one who is cold in public but fully devoted to you?",
    "Would you rather find out your partner was in a secret relationship before you or that they are still secretly in contact with their ex?",
    "Would you rather have a partner who never apologizes even when wrong or one who apologizes too much but never changes?",
    "Would you rather know all of your partner's secrets but never be able to tell yours or keep all your own secrets but never know theirs?",
    "Would you rather forgive every lie your partner tells or never be able to lie in your relationship at all?",
    "Would you rather have a wild threesome or a mind-blowing one-night stand with someone out of your league?",
    "Would you rather have sex in front of a live audience or watch yourself on tape with your entire friend group?",
    "Would you rather be tied up and dominated or be the one in full control?",
    "Would you rather only be able to have angry, rough sex or only have slow, sensual lovemaking?",
    "Would you rather get caught having sex in public or accidentally send your boss a full nude?",
    "Would you rather be with someone who's into every kink except yours or someone with zero kinks at all?",
    "Would you rather have an orgasm every time someone touches you or never be able to orgasm again?",
    "Would you rather have to moan uncontrollably every time you talk or scream your partner's name every time you sneeze?",
    "Would you rather have sex in an airplane bathroom or in the middle of a crowded party?",
    "Would you rather have your partner dirty talk non-stop during sex or be completely silent the whole time?",
    "Would you rather have a one-night stand with your ex or let your current partner sleep with their ex?",
    "Would you rather only ever be a giver or only ever be a receiver in bed?",
    "Would you rather be caught watching adult content at work or have your browser history leaked to your parents?",
    "Would you rather be forced to make an adult film that gets leaked or have to watch your parents'?",
    "Would you rather scream out the wrong name during sex or hear your partner scream out someone else's?",
    "Would you rather get a tattoo of your worst hookup's name or never have sex again?",
    "Would you rather have sex in a glass room in public or never have sex again?",
    "Would you rather never use a condom again or never give oral again?",
    "Would you rather have sex with someone who only dirty talks in a cringe way or never speaks at all?",
    "Would you rather sleep with someone who is gorgeous but terrible in bed or average-looking but the best sex ever?",
    "Would you rather be forced to sext your boss or accidentally send your mom a full nude?",
    "Would you rather have sex with your biggest turn-off or have your partner tell you you're bad in bed?",
    "Would you rather have sex every day but never finish or only have sex once a year but with the best orgasm of your life?",
    "Would you rather roleplay as a stranger every time or always have to call your partner \"Daddy/Mommy\"?",
    "Would you rather be blindfolded for every sexual encounter or handcuffed every time?",
    "Would you rather have your nudes leaked to the entire internet or walk in on your parents having sex and have them see you?",
    "Would you rather have a partner who only talks dirty in baby voice or one who calls you by your full legal name in bed?",
    "Would you rather have sex in a freezing cold room or in a room that's way too hot?",
    "Would you rather only be able to have sex to cartoon theme songs or elevator music?",
    "Would you rather have to narrate your own sex life in real-time or have your best friend do it for you?",
    "Would you rather be forced to make an OnlyFans or never be able to watch adult content again?",
    "Would you rather have one-night stands with strangers forever or be stuck in a sexless relationship forever?",
    "Would you rather have to do it in front of a camera or have your partner describe it in full detail to your parents?",
    "Would you rather have to use food in the bedroom every time or never be allowed to use your hands?",
    "Would you rather be stuck with a partner who won't let you finish or one who finishes in 10 seconds?",
    "Would you rather have sex in the middle of a thunderstorm or while being watched by your ex?",
    "Would you rather have to moan like a pornstar every time or be completely silent no matter how good it is?",
    "Would you rather be walked in on by your best friend or your sibling while having sex?",
    "Would you rather have sex in a haunted house or a church confessional booth?",
    "Would you rather be locked naked outside overnight or accidentally send your entire contact list a full-body nude?",
    "Would you rather have to cheat on your partner once or be cheated on but never find out?",
    "Would you rather watch your best friend hook up with your ex or be forced to hook up with your ex one last time?",
    "Would you rather swap bodies with your partner for a week or swap sex drives with them forever?",
    "Would you rather be caught cheating in public or accused of cheating even though you're innocent?",
    "Would you rather have to tell your deepest, darkest secret to your enemy or be forced to tell your partner every bad thing you've ever done?",
    "Would you rather find out your partner has a secret second family or find out they've been lying about their entire past?",
    "Would you rather be forever trapped in a bad relationship with amazing sex or a perfect relationship with zero sex?",
    "Would you rather be forced to marry someone you hate or be single forever with no sex?",
    "Would you rather never be able to experience love or never be able to experience lust?",
    "Would you rather have every single lie you've ever told revealed or have to listen to everyone else's true thoughts about you?",
    "Would you rather know the exact date you'll die or know how you'll die but not when?",
    "Would you rather lose all your past memories or never be able to make new ones?",
    "Would you rather always feel extreme pain but never die or die instantly but painlessly right now?",
    "Would you rather have eternal life but everyone forgets you or a short but meaningful life where you're remembered forever?",
    "Would you rather be trapped in your worst nightmare forever or live a normal life but have a new fear haunt you every day?",
    "Would you rather be completely alone for the rest of your life or surrounded by fake people who secretly hate you?",
    "Would you rather be forced to watch your worst mistake replayed daily or never remember anything past yesterday?",
    "Would you rather be rich but everyone hates you or poor but everyone adores you?",
    "Would you rather restart your life from birth but keep all your current memories or skip 10 years into the future with $10 million?",
    "Would you rather have infinite knowledge but never be able to share it or be the dumbest person alive but everyone listens to you?",
    "Would you rather save a loved one but 100 strangers die or save 100 strangers but lose your loved one?",
    "Would you rather have to lie to your best friend every day or never be able to lie even when needed?",
    "Would you rather be the reason for someone's death or know someone died because you failed to act?",
    "Would you rather steal $1 million from a stranger or steal $100 from your best friend?",
    "Would you rather be hated for something you didn't do or loved for something you didn't deserve?",
    "Would you rather be able to stop all crime but never be happy or live in a crime-filled world but be personally happy?",
    "Would you rather always be morally right but hated or morally wrong but admired?",
    "Would you rather be responsible for destroying the world or be the only person who survives its destruction?",
    "Would you rather be able to save one person you love from death or prevent a massive disaster that kills thousands?",
    "Would you rather take full blame for a crime you didn't commit or let your best friend take the fall for something they didn't do?",
    "Would you rather have unlimited money but never feel love or deep love but always struggle financially?",
    "Would you rather have everything you touch turn to gold but never be able to touch another person, or be poor but loved by all?",
    "Would you rather have absolute power over the world for a year or be a regular person but truly happy forever?",
    "Would you rather be able to buy anything but never enjoy it or have the best experiences but never afford anything you want?",
    "Would you rather win the lottery but be forced to leave everyone you love behind or stay with them but always be broke?",
    "Would you rather have infinite wisdom but be unable to use it or have great wealth but lose all emotions?",
    "Would you rather work a miserable high-paying job or a dream job that barely pays the bills?",
    "Would you rather be loved by millions but secretly miserable or completely unknown but deeply content?",
    "Would you rather have a billion dollars but only live for 10 more years or be immortal but always poor?",
    "Would you rather be a successful fraud who never gets caught or an honest failure who is constantly judged?",
    "Would you rather know everyone's thoughts but never be able to turn it off, or have everyone know your thoughts all the time?",
    "Would you rather have to relive your most painful moment over and over or never feel happiness again?",
    "Would you rather be trapped in a time loop of the worst day of your life or be stuck reliving an average boring day forever?",
    "Would you rather be able to pause time but age normally or rewind time but lose a year of life every time you do?",
    "Would you rather be able to see the future but unable to change it or able to change the past but with unintended consequences?",
    "Would you rather be forced to relive every embarrassing moment of your life in a loop or have everyone see them on a public screen?",
    "Would you rather always say exactly what you're thinking or never be able to speak again?",
    "Would you rather erase your worst memory but lose a great one or keep all your memories, including the painful ones?",
    "Would you rather never sleep again but never feel tired or have to sleep 20 hours a day?",
    "Would you rather wake up as a completely different person with no memories or live your life knowing it was all a simulation?",
    "Would you rather be the only person who remembers the past or the only one who can see the future but no one believes you?",
    "Would you rather be able to live in any fictional world but never return or stay in reality but control everything around you?",
    "Would you rather be trapped in a video game world where death is permanent or stuck in a never-ending dream?",
    "Would you rather have the ability to read minds but go insane or control minds but lose your own identity?",
    "Would you rather be able to jump into any book and live its story or jump into any movie but never return to real life?",
    "Would you rather be able to swap bodies with anyone at will but only for 1 hour or live in someone else's body permanently?",
    "Would you rather wake up as the richest person alive but be hunted by assassins or become a superhero but have your family taken hostage?",
    "Would you rather gain superhuman intelligence but be completely alone or have a perfect life but lose 50 IQ points?",
    "Would you rather be able to teleport anywhere but never be able to stay in one place for more than a day or be invisible but only when no one is looking?",
    "Would you rather live forever but everyone forgets you exist or live a perfect life but die in 10 years?",
    "Would you rather have mind-blowing one-night stands forever or a committed relationship but average sex?",
    "Would you rather have a partner who is amazing in bed but toxic in life or loving and supportive but bad in bed?",
    "Would you rather be in a relationship where you can never touch each other or one where you can only touch but never emotionally connect?",
    "Would you rather never be able to finish but enjoy the build-up forever or get straight to the end every time but no build-up?",
    "Would you rather have a partner who is wild in private but reserved in public or one who is openly flirty but vanilla in private?",
    "Would you rather have passionate nights but no emotional connection or deep emotional intimacy but no physical intimacy?",
    "Would you rather only be able to do it in public places but never get caught or only in private but someone always hears?",
    "Would you rather always have to wear lingerie/boxers in public or never be able to wear underwear again?",
    "Would you rather be in a dominant-submissive relationship forever or have no control over your pleasure at all?",
    "Would you rather be with someone who is obsessed with trying new things constantly or only does the same routine every time?",
    "Would you rather have a secret affair that never gets discovered or be completely loyal but your partner always suspects you?",
    "Would you rather have your wildest secret exposed publicly or be forced to hear your partner's every past experience in detail?",
    "Would you rather have a sex tape of yours leaked or accidentally leak a close friend's tape?",
    "Would you rather never be able to self-pleasure again or never have a partner again?",
    "Would you rather have to describe every intimate experience to your parents or listen to them describe theirs?",
    "Would you rather have to send spicy texts to your boss or accidentally send a pic to your mom/dad?",
    "Would you rather have to walk around naked for an hour in your neighborhood or be handcuffed to an ex for 24 hours?",
    "Would you rather be a voyeur (watch but never touch) or an exhibitionist (do it while being watched)?",
    "Would you rather have a secret fling with your best friend's partner or have your best friend hook up with your partner?",
    "Would you rather have a passionate night with your enemy or never experience passion again?",
    "Would you rather have a one-time experience with your ultimate fantasy partner or a lifetime of average experiences with your true love?",
    "Would you rather only be able to do it in complete darkness forever or always have bright lights and a full audience?",
    "Would you rather be with someone who is aggressive and dominant in bed or completely submissive and follows your every command?",
    "Would you rather have to role-play as a stranger every time or never be able to change positions again?",
    "Would you rather only be able to use toys forever or never be able to use them again?",
    "Would you rather have your partner handcuffed to you for a full day or be blindfolded every time?",
    "Would you rather have to moan loudly in public every time you hear your name or accidentally send a spicy voicemail to your entire contact list?",
    "Would you rather have a wild one-night stand with a celebrity or a secret long-term affair with someone you shouldn't be with?",
    "Would you rather only be able to be intimate outdoors or only in complete silence?",
    "Would you rather be in a relationship where you can never say no to your partner's requests or where they can never say yes to yours?",
    "Would you rather be blackmailed with an intimate video or have to blackmail someone else?",
    "Would you rather be caught by your parents or accidentally walk in on them?",
    "Would you rather have a wild experience with your boss for a promotion or be stuck in a terrible job forever?",
    "Would you rather have your partner secretly recording everything or have to record and send proof of everything to them?",
    "Would you rather have a \"truth serum\" make you confess all your fantasies or have all your browser history leaked?",
    "Would you rather be tied up and teased forever without finishing or never experience teasing again?",
    "Would you rather only be able to do it in a car forever or never be able to do it outside a bed again?",
    "Would you rather have your intimate moments live-streamed to the world or be banned from intimacy forever?",
    "Would you rather accidentally say your ex's name in bed or have your partner say someone else's name?",
    "Would you rather have to describe your wildest fantasy to a group of strangers or act it out once in front of them?",
    "Would you rather have a wild experience with your friend's partner or have your best friend do it with your partner?",
    "Would you rather have a fantasy come true but can never do it again or never experience it but always dream about it?",
    "Would you rather have a partner who is always louder than necessary or one who never makes a sound?",
    "Would you rather be forced to share every spicy detail of your experiences with your coworkers or never be able to do it again?",
    "Would you rather have to watch spicy movies with your family or watch your own tape with them?",
    "Would you rather be the star of an underground adult film or direct one for someone else?",
    "Would you rather only be able to do it in extreme weather conditions or never again if it's not in a perfect setting?",
    "Would you rather have a partner who talks dirty nonstop during it or one who is completely silent the whole time?",
    "Would you rather have a one-time secret experience with a married person or be in a long-term love affair with someone off-limits?",
    "Would you rather be a master of teasing but never finish or always finish too quickly but with no control?",
    "Would you rather be completely owned by someone who controls everything you do or own someone who obeys your every command?",
    "Would you rather be chained up and teased for hours with no release or be in full control but unable to feel anything?",
    "Would you rather be forced to beg for pleasure or have someone beg you for it?",
    "Would you rather have a secret underground dungeon for your deepest fantasies or be forced to experience someone else's darkest fantasy?",
    "Would you rather be collared and marked as owned forever or own someone who is devoted to your pleasure only?",
    "Would you rather be denied pleasure for a whole year or be unable to stop yourself from craving it all the time?",
    "Would you rather be forced to obey someone's every demand for 24 hours or have full control over someone else for a week?",
    "Would you rather have to wear a tracking device that lets someone control when and how you feel pleasure or be able to control someone else's pleasure with a remote?",
    "Would you rather never be able to touch again but always be craved or have endless pleasure but never feel truly desired?",
    "Would you rather be kept as a personal secret, hidden from the world or be someone's ultimate public obsession?",
    "Would you rather have an intense one-night secret affair with someone dangerous or a long-term secret affair with someone completely off-limits?",
    "Would you rather share your darkest fantasy with a stranger or have your best friend accidentally discover it?",
    "Would you rather have a wild night with someone forbidden (teacher, boss, best friend's partner, etc.) or never experience fantasy fulfillment?",
    "Would you rather have a hidden relationship with someone you shouldn't be with or be in an open relationship where your partner does whatever they want?",
    "Would you rather have a tape of your wildest night leaked or have your deepest secret fantasy revealed to the world?",
    "Would you rather be in a relationship where you can never say no to anything or one where your partner is completely at your mercy?",
    "Would you rather have a secret online identity to explore your darkest desires or be forced to live out your fantasies in real life with no way to hide?",
    "Would you rather have to publicly confess your darkest kink or be blackmailed into doing it once?",
    "Would you rather be blindfolded and taken wherever someone desires or be in full control but never feel surprise again?",
    "Would you rather be teased endlessly but never satisfied or get everything instantly but never feel the build-up?",
    "Would you rather experience intense pleasure but never be able to stop or be denied pleasure but crave it forever?",
    "Would you rather be completely helpless and at someone's mercy or have someone completely helpless at your command?",
    "Would you rather have a partner who loves to push your limits in private or one who teases you in public but keeps it mild behind closed doors?",
    "Would you rather be forced to endure hours of teasing with no release or be overstimulated to the point of exhaustion?",
    "Would you rather have to submit to your deepest, darkest fantasy once or be denied any fantasy forever?",
    "Would you rather be punished for every mistake you make or rewarded for every time you give in?",
    "Would you rather be in a scenario where you're not allowed to speak or resist or one where you control someone who can't refuse?",
    "Would you rather have to wear a hidden pleasure device controlled by someone else or be forced to control someone else's without them knowing?",
    "Would you rather experience pain mixed with pleasure forever or only be allowed to have pleasure once a year?",
    "Would you rather be trapped in a room with someone who controls you completely or be the one controlling someone but unable to stop?",
    "Would you rather be teased in public where no one notices or do something wild in private but be filmed?",
    "Would you rather have to wear something risqué in a professional setting or have to hide something extremely inappropriate on your body all day?",
    "Would you rather be forced to do something public but subtle or be in private but so loud everyone hears?",
    "Would you rather be a famous secret fantasy to others or be obsessed with someone who doesn't know you exist?",
    "Would you rather be completely exposed in front of an audience or watch someone else experience the same with no control?",
    "Would you rather have to sneak around and never get caught or be forced to be completely open but judged for it?",
    "Would you rather have a secret room full of forbidden pleasures or have unlimited access to others' secrets but never your own?",
    "Would you rather be teased in front of others but no one knows or have to keep your desires a secret forever?",
    "Would you rather have to do something wild on camera but never see it again or be forced to watch others do it while never participating?",
    "Would you rather have every thought of yours exposed to your partner or never know what they're secretly thinking?",
    "Would you rather be able to erase all your forbidden fantasies but lose your passion or live them out once but have to keep them a secret forever?",
    "Would you rather have a wild experience with someone twice your age or someone much younger but fully consenting?",
    "Would you rather be locked in a room with your biggest desire or be given full control over someone else's biggest desire?",
    "Would you rather have your deepest fantasy written as a best-selling book or acted out as an underground secret film?",
    "Would you rather have to act out your darkest desire once or never experience passion again?",
    "Would you rather have someone you barely know control you completely or be able to control someone you're obsessed with but never touch them?",
    "Would you rather be trapped in a room where you have to obey every command or be the one giving every command with no refusal?",
    "Would you rather experience your wildest fantasy but never tell anyone or only be able to dream about it but never live it?",
    "Would you rather be completely restrained with no way to stop or be the one restraining someone with full control?",
    "Would you rather have your darkest fantasy played out once but erased from memory or never experience it but remember every detail?"
];

function getRandomNumber3() {
    return Math.floor(Math.random() * wouldYouRatherQuestions.length)
}